platform = "ollama"
model = "deepseek-coder-v2:16b"
api_key = "your api key"

# ollama 参考:
# platform = "ollama"
# model = "deepseek-r1:8b"
# api_key = "your api key"

# ollama 参考:
# platform = "ollama"
# model = "qwen3-coder:30b"
# api_key = "your api key"
