platform = "ollama"
model = "qwen2.5-coder:7b"
# model = "gpt-oss:20b"
# model = "deepseek-coder-v2:16b"
# model = "deepseek-r1:8b"
api_key = "your api key"
api_base_url = "http://127.0.0.1"
api_port = "11434"
